### ISSUE TITLE
Verify: require cert to match committer?

### ISSUE THREAD

**Issue by wlynch** [sigstore/gitsign#104]
This could be a disruptive change to users, so looking for feedback before we commit to this - should we require by default that the cert contained in the git commit match the email of the git committer?

Right now we just check for a valid signature, and users would need to add additional checks to verify the identity matches.

This would be in line with [Sigstore clients should require a provided identity](https://docs.google.com/document/d/1o8_bXIygufgiohJGlmBzqF4_BnXCTfgh4ILgJFJxYRs/edit?resourcekey=0-YEar3v67uoT31kj83dCVvA#) by @haydentherapper and @znewman01, since we don't have an easy way to pass additional params via `git verify-commit` or `git log`. This also means we don't have a good way to specify the OIDC provider or Sigstore instance, so we may need additional out of band config (i.e. envvar / https://github.com/sigstore/gitsign/issues/99) for this to be complete.

https://github.com/sigstore/gitsign/issues/65 may be a hard requirement here, since otherwise we won't be able to generate privacy preserving certs. We could also provide an option to disable this behavior (though prefer not to do this if possible).

Thoughts? cc @imjasonh @nsmith5

**Comment by znewman01** [comment]
Yeah, I think the default of "check that *someone* signed but not *who*" is pretty dangerous in general and I strongly support being able configure a "verification policy" (with some sensible default; I think the proposed policy is a good one). Options include:

- must be signed by the Git commit email (need to think about how to handle merge commits)
- "unsafe": the behavior today
- allowlist of identities: only trust commits signed by specific Fulcio identities

**Comment by dlorenc** [comment]
I like this in general. Another check we could add is that the timestamp in the commit is during the validity window of the cert, to prevent signing "backdated" commits.

**Comment by wlynch** [comment]
Some more thinking about this - using committer emails to verify against for human users should be relatively easy, but we still need to figure out:

1. What IdP to trust for the email
2. What email to use for commits made by automation
    
    For GitHub Actions: https://github.com/orgs/community/discussions/26560 suggests we can use `41898282+github-actions[bot]@users.noreply.github.com` to link commits to the [GitHub Actions user](https://api.github.com/users/github-actions%5Bbot%5D), but this doesn't help us ID the workflow claims to verify, and also requires users to be setting this when making commits, which probably isn't reasonable to assume is being done broadly.

I'm thinking we'll probably need to make a new `gitsign verify` subcommand to match cosign, though we might be able to populate the committer email by default, which users could then override for verifying automated commits.

**Comment by znewman01** [comment]
> 1. How to find what IdP to trust for the email

Oof, this is really tricky and important to get right. There's [no canonical IdP for a given email](https://github.com/sigstore/fulcio/issues/639) (see also https://github.com/sigstore/cosign/issues/1947).

<warning: I'm going to repeat myself a bunch below 😄 >

That said: I think we can push this problem to wherever we're solving the problem of "whose commits do I trust, in general?" If you e.g. configure a policy that says "for repo X, I trust `*@example.com` and `support@microsoft.com` we would just pick the IdPs there. Until we've got a story there, we're dangerously close to [checking that there is *some* signature, but not *whose* signature](https://github.com/sigstore/cosign/issues/2056), which is an antipattern.

Not sure if this is technically feasible with the hooks we have into Git, but I think putting the the issuer in the commit would be no worse security-wise than where we are today.

**Comment by wlynch** [comment]
Did something thinking + experimentation around this - here's a rough proposal:

For `gitsign verify`, we can provide customized flags that match the experience of `cosign verify` (e.g. `--certificate-email`, etc.).  For `git verify-commit` this is a bit more complex, since we can't pass in additional flags and we're limited by the commit data (which is basically user emails).

## User Emails

This is the simplest case, since we should generally have a valid email associated to the commit that should match the cert.

For `git verify-commit`, we can introduce 2 new gitsign options:

1. `gitsign.verifyPolicy` that can take the following values (bikeshedding welcome):

    Value | Description
    -|-
    emailOnly (default) | Only validate email matches cert. If provided, gitsign will output a warning that the signature cannot be fully verified unless the identity provider is also checked, but will still pass. Users will be recommended to use `gitsign verify` instead.
    strict | Require strict identity provider checking. This requires that the cert identity must be issued by a provider in `gitsign.identityProviders` and will prompt users to use `gitsign verify` on failure.

2. `gitsign.identityProviders` - a comma separated list of allowed identity provider mappings, specified by `domain:idp` i.e. `gmail.com:https://accounts.google.com`

This allows us to keep compatibility with existing git workflows while still giving users control to restrict down usage. It's probably unreasonable to require users to pre-configure the list of identity providers per repo, since this may vary per repo or even per user.

## Robot emails

Automated workflows (Kubernetes, GitHub Actions, etc.) present more of a challenge, because we don't have a clear email to use for each service account user.

For these cases, we propose allowing tools to set specialized Git committer user names that gitsign will know how to interpret. These should match the identity formats [we are aiming to support for other tools](https://github.com/sigstore/fulcio/issues/716) (e.g. cosign). Gitsign will need to parse the identifiers to extract them and compare against the claims included in the cert. We can reuse the `gitsign.identityProviders` config to map allowed identity providers.

e.g. for GitHub Actions, the way to attribute commits to actions is to use the special [`41898282+github-actions[bot]@users.noreply.github.com` email](https://github.com/orgs/community/discussions/26560) where 41898282 is the GitHub User ID of GitHub Actions: https://api.github.com/user/41898282

With this, we could have gitsign clients populate a special username + email - i.e. `github://sigstore/gitsign:refs/heads/main:workflow.yml <41898282+github-actions[bot]@users.noreply.github.com>`, where `github://sigstore/gitsign:refs/heads/main:workflow.yml` represents the Service Account identifier (actual spec TBD - follow https://github.com/sigstore/fulcio/issues/716 for the real spec)

NOTE: technically user names in emails should be max 64 characters, but since we're using this primarily for signature validation and service account identities will likely have noreply emails associated with them anyway, we are ignoring this restriction w.r.t. git and gitsign verification. For email based git workflows, the user name can be truncated if necessary - we're considering the git repo itself to be the source of truth for validation.

### Alternatives 

We've observed that GitHub is actually quite a bit permissive in what emails it lets you associate (`asdf` is just arbitrary text):

Email | GitHub Shows Actions User
-|-
`41898282+github-actions[bot]@users.noreply.github.com` | ✅ 
`41898282+github-actions[asdf]@users.noreply.github.com` | ❌ 
`41898282+asdf@users.noreply.github.com` | ✅ 
`41898282+asdf[bot]@users.noreply.github.com` | ✅ 
`41898282+github-actions[bot]+asdf@users.noreply.github.com` | ❌ 
`41898282+asdf+github-actions[bot]@users.noreply.github.com` | ❌ 

We could use this to include identity information in the email itself, but since we don't control the domain this feels much riskier to rely on for stability without GitHub's blessing.

**Comment by operatorequals** [comment]
Inspired by this Issue, I created a Github Action that tries to catch all possible scenarios of signed (and unsigned) commits
that violate security.

In the [README's scenarios section](https://github.com/operatorequals/gitsign-action#scenarios-mitigated-by-sigstore-gitsign-along-with-this-github-action) there are some cases that this Github Action would fail to verify a signed commit, given some security assumption.

The Github Action
https://github.com/operatorequals/gitsign-action
