### ISSUE TITLE
Select auth provider with config

### ISSUE THREAD

**Issue by wlynch** [sigstore/gitsign#114]
Probably dependent on #99, but something that would be nice is if we had a way for users to pre-select the auth provider they want to use for a repo.

Currently we use the default interactive provider, but if we had a per-repo config, then we could have an option to specify the TokenGetter to use https://github.com/sigstore/sigstore/blob/2ec832bbea880d6fb3f7b0b7cdfaffde490c571e/pkg/oauthflow/flow.go#L68-L73

Would still require a browser window to go through the oauth flow, but would save a click if you already knew what you wanted to use.

**Comment by imjasonh** [comment]
+1 for adding this to gitsign, and we should make sure it's something we can share with cosign and other tools too using the same convention. Maybe some env var `SIGSTORE_OAUTH_SELECT=google` or something?

**Comment by wlynch** [comment]
> +1 for adding this to gitsign, and we should make sure it's something we can share with cosign and other tools too using the same convention. Maybe some env var `SIGSTORE_OAUTH_SELECT=google` or something?

Started with `GITSIGN_CONNECTOR_ID` in #122, though wouldn't be opposed to `SIGSTORE_CONNECTOR_ID`. 

Not 100% sure if we want to support things like `google` though (as opposed to `https://accounts.google.com` - these are really URL params that are being sent to Dex, so we probably want Dex to be the arbiter of what are allowed values, since these could change per instance.
