### ISSUE TITLE
Missing access_token causes internal server error

### ISSUE THREAD

**Issue by JonZeolla** [sigstore/gitsign#131]
**Description**

<img width="527" alt="Screen Shot 2022-09-06 at 6 57 55 PM" src="https://user-images.githubusercontent.com/1385510/188754606-e9acd4d5-531a-4a8b-8855-29d37f8c21ba.png">

**Version**

gitsign version v0.2.0

**Comment by wlynch** [comment]
My bet is this is related to the ongoing GitHub outage https://www.githubstatus.com/incidents/wl09fvhb20x8 and GitHub is failing to return the OAuth token to Dex. This might be a wait and see until the outage clears 🤷 

cc @haydentherapper

**Comment by haydentherapper** [comment]
That would make sense, there have been no other changes to the auth infrastructure that would be causing this. I assume it’s been resolved by now.

**Comment by JonZeolla** [comment]
Yeah makes sense.  Wasn't sure if the project wanted to handle that more gracefully.  If not you're welcome to close as won't fix

**Comment by wlynch** [comment]
Since we're pretty sure this was related to the github incident, closing this out. Thanks for the report! 🎉
