### ISSUE TITLE
`gitsign --version` runs only inside a git repository

### ISSUE THREAD

**Issue by PickledDragon** [sigstore/gitsign#154]
**Description**
I have followed the installation guide [here](https://docs.sigstore.dev/gitsign/installation/#installing-gitsign-with-homebrew) and installed `gitsign` on my Macbook. The next step in the guide [checking the installation](https://docs.sigstore.dev/gitsign/installation#checking-your-installation) recommends to run `gitsign --version` to check the installation. If I do that from a random directory, the command fails with an error message `repository does not exist`.

**Steps to reproduce**
Precondition: The environment already has `gitsign` installed.
* Create a new directory and change to it `cd $(mktemp -d)`
* Run `gitsign --version`
* You'll get an error 'repository does not exist'

**Expected behaviour as per the [docs](https://docs.sigstore.dev/gitsign/installation#checking-your-installation)** : Gitsign prints out version number.

**Version**
v0.3.1

**Additional Information**
* If I initialize a git repo(`git init`) in the newly created temp directory and runs `gitsign --version` I do get the expected output
* If I change to an existing git repo on the disk, I get the expected output
* When using `--version` and `--help` switches, I think it is to much to demand that the end user needs to do that in a git repo
* It could trip new users

**Comment by wlynch** [comment]
Conveniently I think this was also fixed by https://github.com/sigstore/gitsign/pull/149 :) 

Cutting v0.3.2 now, but otherwise feel free to install from main!

**Comment by PickledDragon** [comment]
Thanks I'll give it a shot on the weekend.

**Comment by PickledDragon** [comment]
Thanks @wlynch [v0.3.2](https://github.com/sigstore/gitsign/releases/tag/v0.3.2) fixes it. I am closing this issue.
