### ISSUE TITLE
Support users who SSH into a remote server

### ISSUE THREAD

**Issue by imjasonh** [sigstore/gitsign#190]
SSHing into a remote machine to develop is a fairly common workflow.

```
ssh me.corp.biz
git init # and setup gitsign
echo foo > README
git commit -am "just fooing"
```

Unfortunately the UX in this case is somewhat suboptimal, though it has improved greatly. Instead of popping up a browser window like it would if you were `git commit`ing locally, this prints a URL and asks you to open in a browser you have access to, whereupon you OAuth, and copy a code back to the waiting gitsign prompt to continue.

This isn't bad (and again, it's much improved!), but it means quite a few more manual steps for each commit: copy/paste URL, the usual OAuth, copy/paste auth code.

To make this easier, it could be cool to provide a local agent that connects to the remote agent over SSH, and listens for browser-open requests, then opens a (local) browser window, gets the token, then sends it back over that same connection to the remote gitsign instance, where it's exchanged for a cert. Or, maybe, the local agent trades the token for the cert and passes only the cert, I don't know.

In any case, I think most of this code already exists in some form already, between gitsign and the cred cache, it's just about packaging it differently, and configuring the handoffs between the local agent and the remote gitsign, without sacrificing security.

**Comment by datosh** [comment]
I ran into the same limitations @imjasonh since I am exclusively working with "remote" machines. Either cloud machines or locally virtualized. [I've written down my thoughts on medium](https://medium.com/p/6f40f47d289f) on how to solve this using a NAT gateway or SSH tunnels. Which gives you exactly the same UX as you would get locally. 

Which security guarantees could an agent provide in contrast to SSH tunnel? Or would they be equivalent in security and help the user set this up easily?

**Comment by dprotaso** [comment]
For some reason I also notice that I need to redo the auth flow on every commit. Unsure why if that's because I'm remote.

I configured `gitsign` for a single repo - not globally

**Comment by wlynch** [comment]
> Which security guarantees could an agent provide in contrast to SSH tunnel? Or would they be equivalent in security and help the user set this up easily?

I'd say more the latter - making things easier to setup and use.

> For some reason I also notice that I need to redo the auth flow on every commit. Unsure why if that's because I'm remote.

That should only be the case if you're not using the cache - each commit is considered a unique signing event.

**Comment by dprotaso** [comment]
Following up - I also don't mind the gcloud auth flow. The cli will present an URL and then wait on stdin for the user to provide a code/token.
