### ISSUE TITLE
OAuth device flow support

### ISSUE THREAD

**Issue by wlynch** [sigstore/gitsign#20]
**Description**

Credit to @philpennock for this idea! We should be able to write directly to /dev/tty to get around the "git eats stdout/stderr" restriction and prompt for device flow. I've already verified a simple print gets through using https://pkg.go.dev/github.com/mattn/go-tty - so we need to:

1. Refactor the code to plumb the TTY writer through to the device flow
2. Figure out a way to distinguish browser capable vs terminal only sessions.

For 2 - we can't follow what cosign does here since all invocations of the tool will trip the device flow since the tool is being wrapped by Git.

https://github.com/sigstore/cosign/blob/2e00e8a341ac3a447a8078147db941bd01c4d03c/cmd/cosign/cli/fulcio/fulcio.go#L140-L151

I was thinking maybe we just try opening the browser and if it fails, fall back to device flow? I'm just worried we might hit weird edge cases where a terminal based browser may try and open though. Open to ideas here!

**Comment by dln** [comment]
The oidc-login plugin for kubectl might be a good source of inspiration?

https://github.com/int128/kubelogin
