### ISSUE TITLE
Batch signing support

### ISSUE THREAD

**Issue by wlynch** [sigstore/gitsign#21]
**Description**

This is probably a broader sigstore feature request, but creating an issue here to track.

An annoyance with using gitsign today is you need to hop through the oauth flow for every commit - this can be very tedious for quick `git commit --amend`s or multi-commit rebases.

We'll want to look into some way to cache the signing keypair (or possibly the Fulcio OIDC token) to support multiple operations for the lifetime of the keypair (~10 mins) without needing to hop through the flow again and get a new key. This key shouldn't hit disk.

https://git-scm.com/docs/git-credential-cache strikes me as something similar to model off of for ideas.

Related discussion: https://sigstore.slack.com/archives/C01PZKDL4DP/p1652208232815029

**Comment by embano1** [comment]
Thx for tracking this here as it was literally the first question I had when reading through the value prop 👍

**Comment by chaodaiG** [comment]
Thank you for raising this, this is also my immediate feeling when trying out gitsign(have a git alias `append=commit amend --no-edit` and use it much more often than `git commit`)
