### ISSUE TITLE
Add RFC3161 timestamps to signatures?

### ISSUE THREAD

**Issue by wlynch** [sigstore/gitsign#22]
**Description**

[We should be able to add RFC3161 signed timestamps into signatures pretty easily](https://pkg.go.dev/github.com/github/smimesign/ietf-cms#SignedData.AddTimestamps).

Rekor does provide a timestamping authority today, but it's currently going through some changes that we would need to track, and potentially we might need to use another TSA altogether - https://github.com/sigstore/rekor/issues/812

cc @nsmith5 @haydentherapper @dlorenc Any thoughts here? Is this something worth adding or is it not worth it?

**Comment by haydentherapper** [comment]
Why do we need signed timestamps? Are we gaining much benefit from this? If we're publishing the commit to the log, we have a witness to the signing. The added timestamp transparency doesn't add much.

RFC 3161 is also an old complex standard. I'd prefer to not proliferate its use.

**Comment by dlorenc** [comment]
I think here it's about compatibility. Git requires x509 s/mime signatures here and assumes RFC3161.

**Comment by haydentherapper** [comment]
If we're stuck with RFC 3161, then I'd recommend using a third-party TSA, probably not by default and probably making it configurable.

On the note of by default, this gets back to the larger question around the benefit of timestamping. It reduces the need for trusting the timestamp from Rekor, but there may be other ways to guarantee Rekor's clock is trustworthy. I'm fine with this an option for users that want to use timestamping, but I'd probably say to make this optional and off by default.

**Comment by haydentherapper** [comment]
Planning to take a look at spinning up a rfc3161 server soon. I don’t think this is blocked though, you can easily use a third party TSA, and frankly it’s a better trust model since you aren’t relying on Sigstore to provide the signature over the time.
