### ISSUE TITLE
`gitsign --version` shows `unknown`

### ISSUE THREAD

**Issue by LeSuisse** [sigstore/gitsign#24]
Hi,

I just started to play a bit with `gitsign` to start packaging it for `nixpkgs` and I noticed that when using the binaries in the release assets the version was not set:
```
$ ./gitsign_0.0.2-alpha_linux_amd64 --version
unknown
```

I did not check the build pipeline but since it relies on VCS information retrieved from the `debug/buildinfo` I am guessing it will not play well with 107ac2485733ef71c8dce26ade70c68879bcdb45 anyway.

https://github.com/sigstore/gitsign/blob/107ac2485733ef71c8dce26ade70c68879bcdb45/main.go#L76-L88

**Comment by cpanato** [comment]
I will take care of this

**Comment by tech189** [comment]
I just installed 0.1.0 on Windows and the output is still `unknown`:
```
❯ gitsign --version
unknown
```

**Comment by cpanato** [comment]
> I just installed 0.1.0 on Windows and the output is still `unknown`:
> 
> ```
> ❯ gitsign --version
> unknown
> ```

this PR will address this https://github.com/sigstore/gitsign/pull/66
