### ISSUE TITLE
IDE plugins / extensions

### ISSUE THREAD

**Issue by lukehinds** [sigstore/gitsign#26]
Would be nice to have an extension for vs-code, and perhaps a plugin for vim / JetBrains?

**Comment by wlynch** [comment]
Following up on this - you should be able to use existing Git plugins with gitsign with no additional modifications. gitsign is configured with standard [Git configs](https://git-scm.com/docs/git-config), which IDEs should respect.

Certain IDEs may let you configure additional options on a per editor basis (e.g. VSCode's `git.enableCommitSigning: true` setting), but these will almost always be additional configs on top of the user's gitconfig.
