### ISSUE TITLE
Support for oidc client secret config

### ISSUE THREAD

**Issue by walmav** [sigstore/gitsign#365]
Certain OIDC providers require client secret to be passed during authflow. 
 
 Please add ClientSecret in the config and propagate it through the authflow:
https://github.com/sigstore/gitsign/blob/b156dfa92ec8ce881c8090de6b74a1b71132da14/internal/config/config.go#L41

**Comment by rafaeltuelho** [comment]
@walmav I think I hit this issue when using Google oAuth2. See my question here https://github.com/sigstore/gitsign/discussions/532

Is there any way to work around this? How do I pass this client secret when using Google as an auth provider?

Thanks.
