### ISSUE TITLE
feat: make container image of gitsign

### ISSUE THREAD

**Issue by developer-guy** [sigstore/gitsign#46]
**Description**

Will you make a container image of gitsign with practices that you are using for other sigstore projects such as using ko or another tool, I'm willing to do this.

cc: @cpanato

**Comment by derekmurawsky** [comment]
> It's definitely possible, but I wonder how you'd anticipate using it. Can you give some more detail about your use case?

I can think of one - In a build process you want to easily sign a release. Many use containers to better manage the complexity of build agent software and dependencies. That same container could be used with pre-commit frameworks to allow for signing locally as well, without the need to install anything besides a container runtime, which many people already have.

**Comment by wlynch** [comment]
Circling back on some of the older issues...

Not opposed to this if someone wants it and can implement it! Using ko + layer on top of https://github.com/distroless/git would probably be a good way to get a minimal gitsign image.

For those who are interested in GitHub actions, https://github.com/chainguard-dev/actions/tree/main/setup-gitsign is available to use (bumping to latest in https://github.com/chainguard-dev/actions/pull/147/files)
