### ISSUE TITLE
Cache option for Windows

### ISSUE THREAD

**Issue by Fydon** [sigstore/gitsign#497]
**Description**

Using `git config --global gitsign.connectorID https://github.com/login/oauth` with gitsign and then perform multiple commits can result in reaching the [secondary rate limit](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits) on calling the GitHub repository. Current cache option doesn't work on Windows as mention in #194.

![image](https://github.com/sigstore/gitsign/assets/3404761/3f14a556-60cc-4d78-97c9-a35335e02967)

**Version**

```
gitsign version v0.10.1
parsed config:
{
  "Fulcio": "https://fulcio.sigstore.dev",
  "FulcioRoot": "",
  "Rekor": "https://rekor.sigstore.dev",
  "RekorMode": "online",
  "ClientID": "sigstore",
  "RedirectURL": "",
  "Issuer": "https://oauth2.sigstore.dev/auth",
  "ConnectorID": "https://github.com/login/oauth",
  "TokenProvider": "",
  "TimestampURL": "",
  "TimestampCert": "",
  "LogPath": "",
  "CommitterName": "Foo",
  "CommitterEmail": "Bar",
  "MatchCommitter": false,
  "Autoclose": true,
  "AutocloseTimeout": 6
}
```

**Comment by wlynch** [comment]
I'm open to this, but I do not have any sort of Windows socket experience (or much experience building Windows apps in general). 😓 

The first step would be to hide unix-specific syscalls behind a build flag:

```sh
$ GOOS=windows go build ./cmd/gitsign-credential-cache
# github.com/sigstore/gitsign/cmd/gitsign-credential-cache
./main.go:43:10: undefined: syscall.Umask
```
