### ISSUE TITLE
golang 1.17 version has the installation error.

### ISSUE THREAD

**Issue by majinghe** [sigstore/gitsign#68]
**Description**

the golang version in `go.md` is `go 1.17`, however the installation will show the below error:
```
./main.go:95:26: info.Settings undefined (type *debug.BuildInfo has no field or method Settings)
```

the code is 

```
	if *versionFlag {
		version := "unknown"
		info, ok := debug.ReadBuildInfo()
		if ok {
			for _, s := range info.Settings {
				if s.Key == "vcs.revision" {
					version = s.Value
				}
			}
		}
		fmt.Println(version)
		return nil
	}
```

For `go 1.17` , the function `debug.ReadBuildInfo()` really do not have `Settings` method, but `go 1.18` has:

```
type BuildInfo struct {
	GoVersion string         // Version of Go that produced this binary.
	Path      string         // The main package path
	Main      Module         // The module containing the main package
	Deps      []*Module      // Module dependencies
	Settings  []BuildSetting // Other information about the build.
}
```

So, should the version in go.mod will be changed to `1.18`?

**Comment by imjasonh** [comment]
We should update the installation instructions.

AFAIK the version in `go.mod` doesn't mean "minimum version needed to build this module", it means "which go version's modules behavior should be used" so I think that could stay at 1.17 (or bump to 1.18, they're the same I think).

**Comment by majinghe** [comment]
@imjasonh Thanks for your info, i will close this info.
