### ISSUE TITLE
Does gitsign support signing an annotated tag?

### ISSUE THREAD

**Issue by simonbaird** [sigstore/gitsign#76]
**Question**

If not, are there any plans to do that in future?

**Comment by imjasonh** [comment]
I believe this should already work, if you `git tag -a --sign`, or `git config --local tag.gpgsign true`.

Perhaps this is just something we need to document better.

If you try it out and it doesn't work, let me know.

**Comment by imjasonh** [comment]
Looking through [`git-config`](https://git-scm.com/docs/git-config#Documentation/git-config.txt) a bit more, it looks like there's also [`push.gpgsign`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushgpgSign) which we should maybe test out and document as well.

**Comment by simonbaird** [comment]
Awesome, thanks.

**Comment by wlynch** [comment]
Yes! Gitsign works with tags as well - no additional changes should be needed beyond the initial Gitsign setup (same as commit signing). We should add this to our docs.

Fun fact: Gitsign release tags are already signed with Gitsign. 😎  

```
$ git verify-tag v0.1.1
tlog index: 2660422
gitsign: Signature made using certificate ID 0x259840a0f2e51910c5fe149fca8a43daa82ba254 | CN=sigstore-intermediate,O=sigstore.dev
gitsign: Good signature from [billy@chainguard.dev]
Validated Git signature: true
Validated Rekor entry: true
```
