### ISSUE TITLE
Is GitLab supported

### ISSUE THREAD

**Issue by ChevronTango** [sigstore/gitsign#78]
Much of the documentation and existing issues focus on GitHub but GitLab is a pretty major player as well. What, if any, work is needed for GitLab? Can it be configured to accept GitSign ephemeral certs? What limitations are there to doing this? Is this just browser based or can sn IDE like VS Cose be used?

**Comment by wlynch** [comment]
Hi!

Gitsign works primarily on Git itself, so core Git signing / verification should be able to be used on any Git provider - Gitlab, Gitea, Bitbucket, etc.

Things I know about that might not work specifically on Gitlab:
- Provider verified UI badges - similar to GitHub, if GitLab does not recognize the sigstore root you are using they will show up as unverified on the UI (but you should still be able to verify the commits in your configured client) - 
- Automatic Gitlab CI Runner OIDC signing - this is blocked on GitLab OIDC supporting custom OIDC aud - https://gitlab.com/groups/gitlab-org/-/epics/7335 (this is also true for other Sigstore tools like cosign)

Hope this helps!
