### ISSUE TITLE
Cylance MaxSecure  flagging gitsign_0.1.1_windows_amd64.exe as a trojan

### ISSUE THREAD

**Issue by glennsarti** [sigstore/gitsign#79]
**Description**

Cylance Max Secure is flagging the 64bit gitsign executable as a potential trojan. (`Trojan.Malware.300983.susgen`)

A quick google search has shown that unfortunately this is somewhat common with golang if you pack/unpack DLLs into the exe on Windows. However I can't verify that gitsign, or any it's dependencies, do this.

Other virus scanners have not detected anything.  So I'm somewhat sure it's a false positive in this case.

I'm raising an issue mainly for awareness that other Windows users may encounter this too.

Ref  - https://www.virustotal.com/gui/file/0f026879fae8a7cc503f7829a885ffc14b9d6ae4d52b9086c5ba05b9ca9e1343/detection

**Comment by wlynch** [comment]
Yeah this is bizarre - Gitsign isn't doing any kind of DLL packing. o_O

Apparently antivirus false positives are common enough for Go binaries that Go itself has an FAQ about this - https://go.dev/doc/faq#virus

I don't think we can do much about this on our end - we might need to reach out to the vendor.

**Comment by wlynch** [comment]
I reran the run on the same binary SHA and everything is now green 🤷‍♂️

https://www.virustotal.com/gui/file/0f026879fae8a7cc503f7829a885ffc14b9d6ae4d52b9086c5ba05b9ca9e1343

🎲

**Comment by glennsarti** [comment]
Thanks @wlynch
